/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/nKxwiBySVm7
 */
import {
  CardTitle,
  CardDescription,
  CardHeader,
  CardContent,
  Card,
} from "@/components/ui/card";
import { Button } from "@/components/ui/button";

export function Login() {
  return (
    <div className="flex items-center justify-center min-h-screen bg-gray-100 dark:bg-gray-900">
      <div className="flex w-full h-full">
        <div className="w-1/2 h-full">
          <img
            className="object-cover h-full w-full"
            height="1080"
            src="/placeholder.svg"
            style={{
              aspectRatio: "960/1080",
              objectFit: "cover",
            }}
            width="960"
          />
        </div>
        <div className="w-1/2 h-full flex items-center justify-center">
          <Card className="w-full max-w-md">
            <CardHeader className="space-y-1">
              <CardTitle className="text-2xl font-bold">Login</CardTitle>
              <CardDescription>
                Sign in with your Github account
              </CardDescription>
            </CardHeader>
            <CardContent>
              <div className="space-y-4">
                <Button type="button">Sign in with Githu</Button>
              </div>
            </CardContent>
          </Card>
        </div>
      </div>
    </div>
  );
}
