import type { Metadata } from "next";
import { Exo } from "next/font/google";
import "./globals.css";
import { getServerSession } from "next-auth";
import SessionProvider from "@/components/SessionProvider";
import Navbar from "@/components/component/navbar";
import Image from "next/image";
import HEROBG from "@/assets/home-bg.webp";
import NavTabs from "@/components/component/navTabs";

const exo = Exo({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession();

  return (
    <html lang="en">
      <body className={exo.className}>
        <SessionProvider session={session}>
          <main className="puzz overflow-hidden">
            <Image
              priority
              alt="hero-bg"
              src={HEROBG}
              className="fixed w-full  lg:top-40 top-0 left-0 lg:left-40 -z-10  lg:scale-150 h-screen overflow-hidden"
            />
            <Navbar>
              <NavTabs />
            </Navbar>
            {children}
          </main>
        </SessionProvider>
      </body>
    </html>
  );
}
